# Generated by Django 4.2.6 on 2024-04-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='aadhar_number',
        ),
    ]
